Add gcp and idtoken authenticators
aristanetworks/oidc-authservice pull request #9
Opened 2021-05-28 19:29 UTC by asetty

2021-08-31 01:23 UTC, makofok approved these changes

2021-08-31 09:06 UTC, makofok requested changes

2021-08-31 09:06 UTC, makofok commented on main.go
> +		log.Fatalf("error initializing gcp authenticator")
It would be useful to also emit the actual error
```
log.Fatalf("error initializing gcp authenticator: %v", err)
```

2021-08-31 09:07 UTC, makofok commented on main.go
> +		log.Fatalf("error initializing gcp authenticator")
Actually, do we want it to totally fail if it cannot load the gcp authenticator? Or just log and move on...

```
time="2021-08-31T09:05:06Z" level=fatal msg="error initializing gcp authenticator: error creating validator: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information."
```

2021-08-31 09:21 UTC, makofok commented on main.go
> +		log.Fatalf("error initializing gcp authenticator")
Actually failing on load isn't great either, since then you will have problems in server.go:103 at runtime...

2021-08-31 09:33 UTC, makofok commented on main.go
> +		log.Fatalf("error initializing gcp authenticator")
maybe we can have something like this in main.go
```
	authenticators := []Authenticator{sessionAuthenticator, idTokenAuthenticator}
	if gcpAuthenticator != nil {
		authenticators = append(authenticators, gcpAuthenticator)
	}

...

		caBundle:                caBundle,
		authenticators:          authenticators,
		authorizers:             []Authorizer{groupsAuthorizer},
```

2021-09-01 05:14 UTC, makofok commented on go.mod
> +	google.golang.org/api v0.46.0
I hit https://github.com/googleapis/google-api-go-client/pull/1198 pretty hard while trying to get this branch working locally.

Need to update to v.0.56.0

```
go get google.golang.org/api
...
go get: upgraded google.golang.org/api v0.46.0 => v0.56.0

go mod tidy
```

2021-09-01 05:20 UTC, makofok commented
So I eventually got the googleSAAuthenticator working. See previous notes. For reference I used this method (https://cloud.google.com/iam/docs/creating-short-lived-service-account-credentials#sa-credentials-oidc) to create the idtoken.

I noticed that the current implementation seems to accept _any_ service account:
```
time="2021-09-01T05:11:13Z" level=info msg="UserInfo: &{Name:dummy-client@sw-infra-auth-sandbox.iam.gserviceaccount.com Groups:[]}" host="localhost:8080" ip="192.168.16.1,192.168.16.4" method=GET path=/qotm/
```

2021-11-10 21:30 UTC, kellyma2 commented
Closing this PR - we're going to use client credentials flow for M2M authentication and we'll pull in the idtoken authenticator as part of our updated master branch

2021-11-10 21:30 UTC, closed without merging